### ISSUE TITLE
Checkup / Fixup skip strings

### ISSUE THREAD

**Issue by DanLavine** [maximilien/i18n4go#23]
If T is in the form `gi18n.T("...")` the string will not be recognized by either of these commands.

**Comment by maximilien** [comment]
@DanLavine, same here, can you update the status when you have a second. Thanks.

**Comment by maximilien** [comment]
OK I am doing some cleanup and closing this @DanLavine.

If this is still an issue for you or CLI then create a new issue. Thanks.
