### ISSUE TITLE
fixup improvments

### ISSUE THREAD

**Issue by DanLavine** [maximilien/i18n4go#24]
When running fixup on translations, I would like to have foreign translations be updated with English translations if the ID and Translation are identical in the translation json file. This is because the English string has been updated, but the translation is still in English.

**Comment by maximilien** [comment]
@DanLavine, doing some cleanup. What's the status of this? was it done as part of the fixup command that the CLI team implemented or still missing?

**Comment by maximilien** [comment]
Any update on this @DanLavine? Thanks.

**Comment by maximilien** [comment]
OK I am doing some cleanup and closing this @DanLavine.

If this is still an issue for you or CLI then create a new issue. Thanks.
