### ISSUE TITLE
minor error on flag usage

### ISSUE THREAD

**Issue by bsr203** [maximilien/i18n4go#25]
Not a big issue, but found that flag -p is not working as per the instrution

section: ```https://github.com/maximilien/i18n4go#extract-strings```

command:``` $ gi18n -c extract-strings -v -p -f ./tmp/cli/cf/app/app.go -o ./tmp/cli/i18n -output-match-package```

error: ```flag provided but not defined: -p```

instead, flag --po works

**Comment by maximilien** [comment]
Yup, thanks for reporting this. Fixed the README. The flag `-p` was changed to `--po`.

Fixed. Cheers :beers:
