### ISSUE TITLE
Clarification: what is a 'modified' flag for?

### ISSUE THREAD

**Issue by nota-ja** [maximilien/i18n4go#27]
Hi,

It's not clear for me how a `modified` flag in a language resource JSON file is set / used?

My guess is that it is set to `true` when an original (en_US) text is modified but the translated text is not updated. Am I right?

And thus it should be set to `true` by the tool, not by human, and reset to `false` by human. Is it correct?

**Comment by maximilien** [comment]
@simonleung8 and @jberkhahn,

I believe this was added by CF CLI team. Can you please clarify for @nota-ja 

Thanks,

max

**Comment by jberkhahn** [comment]
Hello,

Yes the 'modified' flag is there to flag new/updated translations that need to have their translations updated. You're correct on the usage of it.

If you'd like to see an example use of the tool and flag in action, we use it to manage the translation files for the Cloud Foundry CLI at http://github.com/cloudfoundry/cli, specifically the script https://github.com/cloudfoundry/cli/blob/master/bin/gi18n-checkup and the translation files kept at https://github.com/cloudfoundry/cli/tree/master/cf/i18n/resources.

Please let us know if you have any more questions.

**Comment by nota-ja** [comment]
I see.
Thanks for clarification.
I don't have any more question right now.
Thank you @maximilien and @jberkhahn .
