### ISSUE TITLE
Duplicate string id should be detected or warned

### ISSUE THREAD

**Issue by zhang-hua** [maximilien/i18n4go#31]
I occasionally find duplicate string id can exist in the same json resource file for one language. This is found when rebasing some code in CLI project for some reason. Perhaps we need a check if it is unique for each string id and reported an error or warning message. Here is an example:

https://github.com/xingzhou/cli/blob/68b153cb9ef90a42e9def2d359d38b83a595e7bb/cf/i18n/resources/fr_FR.all.json#L1473

```
   {
      "id": "Creating service key {{.ServiceKeyName}} for service instance {{.ServiceInstanceName}} as {{.CurrentUser}}...",
      "translation": "Creating service key {{.ServiceKeyName}} for service instance {{.ServiceInstanceName}} as {{.CurrentUser}}...",
      "modified": false
   },
```

https://github.com/xingzhou/cli/blob/68b153cb9ef90a42e9def2d359d38b83a595e7bb/cf/i18n/resources/fr_FR.all.json#L5238

```
   {
      "id": "Creating service key {{.ServiceKeyName}} for service instance {{.ServiceInstanceName}} as {{.CurrentUser}}...",
      "translation": "Creating service key {{.ServiceKeyName}} for service instance {{.ServiceInstanceName}} as {{.CurrentUser}}...",
      "modified": false
   },
```

**Comment by maximilien** [comment]
Hmm, so there is a check for duplicate strings. Can you provide a Golang program where the result is a JSON with duplicates? I have a feeling this duplicate happens after strings are merged so out of band of `i18n4go`...  However, it could also be that there is a bug, and if that's the case, first step is to have a way to replicate the bug. Thanks.

**Comment by maximilien** [comment]
HI, @zhang-hua,

Last chance. Please provide a way to replicate this issue, otherwise, I will close this issue as `invalid`.

Thanks,

@maximilien
