### ISSUE TITLE
assignment to entry in nil map

### ISSUE THREAD

**Issue by fordaz** [maximilien/i18n4go#38]
Something completely unexpected happened. This is a bug in i18n4go.

When running this command:

	i18n4go -c fixup

this error occurred:

	assignment to entry in nil map

and this stack trace:

	/src/github.com/maximilien/i18n4go/i18n4go/i18n4go.go:398 (0x53c2)
		displayCrashDialog: stackTrace := "\t" + strings.Replace(string(debug.Stack()), "\n", "\n\t", -1)
	/github.com/maximilien/i18n4go/i18n4go/i18n4go.go:370 (0x5344)
		handlePanic: displayCrashDialog(err)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:401 (0x3faf5)
		call16: CALLFN(·call16, 16)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:387 (0x17a48)
		gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/hashmap.go:385 (0xc334)
		mapassign1: panic("assignment to entry in nil map")
	/github.com/maximilien/i18n4go/cmds/fixup.go:326 (0x96d71)
		addTranslations: localeMap[id] = common.I18nStringInfo{ID: id, Translation: id}
	/github.com/maximilien/i18n4go/cmds/fixup.go:90 (0x95335)
		(*Fixup).Run: addTranslations(foreignStringInfos, i18nFile[0], foreignMissingTranslations)
	/github.com/maximilien/i18n4go/i18n4go/i18n4go.go:201 (0x4490)
		fixupCmd: err := fixup.Run()
	/github.com/maximilien/i18n4go/i18n4go/i18n4go.go:44 (0x21fb)
		main: fixupCmd()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:63 (0x19593)
		main: main_main()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 (0x41c11)
		goexit:

@yuzhangcmu, @fordaz

**Comment by XenoPhex** [comment]
This may have been fixed in ba76bcdee882.

**Comment by maximilien** [comment]
@yuzhangcmu and @fordaz can you confirm? Otherwise, I will close this.

Thanks @XenoPhex

**Comment by maximilien** [comment]
OK closing this. Please reopen if you see it again. Thx
