### ISSUE TITLE
Is it possible to mark some strings in go source code to be not translated?

### ISSUE THREAD

**Issue by JunliWang** [maximilien/i18n4go#44]
putting strings that I don't want to translate into 1 single json file might also have huge manual workload.
If we have mark strings in go source code, this tool can exclude them when scanning the source files.

**Comment by maximilien** [comment]
@JunliWang indeed, you can include them in the `excluded.json` (even as regular expressions). Anything there will be skipped. Also, please see step 3 in the `typical workflow` for more details.

I am closing this as solved. If you feel otherwise, please reopen. Best.
