### ISSUE TITLE
Strings embedded in two layers of functions are not extracted in extract-string

### ISSUE THREAD

**Issue by XenoPhex** [maximilien/i18n4go#45]
Looks like `extract-strings` is not picking up some cases in the [CF CLI](https://github.com/cloudfoundry/cli) codebase:
```
mkdir lang_temp
i18n4go -c extract-strings -e excluded.json -s specialStrings.json -o lang_temp -f cf/commands/plugin/install_plugin.go
i18n4go -c extract-strings -e excluded.json -s specialStrings.json -o lang_temp -f cf/commands/plugin/uninstall_plugin.go
```
Filename|Category|Line:Example
---------|---------|-------------
|cf/commands/plugin/install_plugin.go|`string` embedded inside a `func`, inside a `func` in a `return`|206:`Plugin name {{.PluginName}} is already taken`
|cf/commands/plugin/uninstall_plugin.go|`string` embedded inside a `func`, inside a `func`|100:`Plugin {{.PluginName}} successfully uninstalled.`

I went through a few dozen cases of missing strings, and it looks like the second case is where most of our strings are missing.

**Comment by maximilien** [comment]
@XenoPhex not able to reproduce. See 6224c7d279213e8e740d29ef1b20277898eefb8d and test for issue #45 and it's able to extract strings fine. I double checked that the example correctly replicates your situation, but please double check and let me know...

Also, I am wondering if your issue is perhaps due erroneous entries in your `excluded.json` or regexp? Can you share those please. Thx.

**Comment by XenoPhex** [comment]
@maximilien I'm looking at the test and it seems valid, I also tried the binary on my local machine (prior tinkering with the test) and it seems to be picking up those strings with/without the `exclusion.json`. I have a weird feeling there might be a problem with the way the binary is compiled on that machine, so I'll take a look on Monday and confirm.

**Comment by maximilien** [comment]
Cool @XenoPhex. I'll close and reopen if you can replicate. Best.
