### ISSUE TITLE
extract-strings for directories overrides files with the same name

### ISSUE THREAD

**Issue by GarfieldIsAPhilosopher** [maximilien/i18n4go#46]
Give the following directory structure:

```
.
├── a
│   └── a.go
├── b
│   └── a.go
└── c
    └── a.go
```

If we call `i18n4go -c extract-strings -o out -d . -r` the result is 1 json file in the out directory, which includes only strings from `c/a.go` and nothing from `a/a.go` or `b/b.go`.

@luan && Difan

**Comment by maximilien** [comment]
Hi, @GarfieldIsAPhilosopher,

Sorry getting to this so late. Thanks for the submission. So this happens also for a single directory?

Best,

Max
